### ISSUE TITLE
Pin mapping table missing a cell

### ISSUE THREAD

**Issue by Frijol** [tessel/t2-docs#113]
![screen shot 2016-09-12 at 10 30 57 am](https://cloud.githubusercontent.com/assets/454690/18439607/0f612116-78d4-11e6-8e39-9b8fa8cbf19b.png)

I haven't investigated, but concerned we're off by 1 somewhere

**Comment by Jeff-Duke** [comment]
@Frijol I did some quick digging and this appears to be an issue in the markdown parser because that last cell is empty.  As soon as data is added to the cell it appears.  https://github.com/chjj/marked/pull/357

**Comment by rwaldron** [comment]
@Jeff-Duke eek! Can someone throw an `&nbsp;` in there?

**Comment by Jeff-Duke** [comment]
@rwaldron @Frijol   - that worked, PR open. - https://github.com/tessel/t2-docs/pull/128
