### ISSUE TITLE
Would be nice to have hardware docs

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-docs#115]
Many people have been asking for more info on hardware-related specifications like maximum input voltage. It would be great to have T2 documentation [akin to existing T1 docs](https://github.com/tessel/hardware).

**Comment by tcr** [comment]
In particular, I would love to see these moved to docs https://github.com/tessel/hardware/blob/master/modules-overview.md

**Comment by johnnyman727** [comment]
We've had other people ask about GPIO output (current) and should include it in the docs.

![screen shot 2016-09-15 at 1 08 39 pm](https://cloud.githubusercontent.com/assets/432909/18559602/058f2e3e-7b46-11e6-9282-22714ae9d723.png)

**Comment by Frijol** [comment]
Lots of good info here https://tessel.io/blog/113259439202/tessel-2-hardware-overview
