### ISSUE TITLE
`t2 key` command is undocumented in CLI docs

### ISSUE THREAD

**Issue by Frijol** [tessel/t2-docs#12]

**Comment by johnnyman727** [comment]
Yeah, I don't really like that command either :/ It was sort of necessary for `t2-vm` though.

**Comment by HipsterBrown** [comment]
For those looking to take on this issue:

Info about the `t2 key` command can be found here -> https://github.com/tessel/t2-cli/blob/master/bin/tessel-2.js#L338-L351

The documentation for this command can go under the "Tessel Management" section under `cli.md` -> https://github.com/tessel/t2-docs/blob/master/cli.md#tessel-management

**Comment by Jeff-Duke** [comment]
PR open - https://github.com/tessel/t2-docs/pull/129
@Frijol @HipsterBrown

**Comment by Jeff-Duke** [comment]
@Frijol @HipsterBrown I've updated the PR for this.  I think it should be ready to merge.
