### ISSUE TITLE
t2 reboot

### ISSUE THREAD

**Issue by rwaldron** [tessel/t2-docs#123]
`t2 reboot` will reboot your Tessel

**Comment by HipsterBrown** [comment]
As @rwaldron mentioned, you can now reboot your Tessel using `t2-cli`. 

The documentation for this new feature can go under the [Tessel Management section](https://tessel.gitbooks.io/t2-docs/content/API/CLI.html) of the CLI docs.

- [ ] edit the [CLI.md](https://github.com/tessel/t2-docs/blob/master/API/CLI.md) to add `t2 reboot` under Tessel Management using @rwaldron's description

Feel free to ping me or post in [Tessel Slack #community channel](https://tessel-slack.herokuapp.com/) with question or if review is needed.

**Comment by Jeff-Duke** [comment]
PR open
