### ISSUE TITLE
GPIO function diagram

### ISSUE THREAD

**Issue by perjg** [tessel/t2-docs#138]
It would be nice to have an mbed style GPIO function diagram for the Tessel 2 board.

Here are two examples:
https://developer.mbed.org/media/uploads/GregC/xfrdm-kl25z_headers2.png.pagespeed.ic.altGnczqQ9.webp

https://developer.mbed.org/media/uploads/star297/xteens3.1-main.jpg.pagespeed.ic.XmOMXz7Ymr.webp

The diagram should show a picture of the Tessel 2 board, with each GPIO pin marked with pin name as well as other functions available on that pin (such as SDA0, SCL0 etc.)

**Comment by Frijol** [comment]
Do you have a suggestion for software that can be used to build this?

**Comment by perjg** [comment]
Inkscape is probably the best free software to use for this.

**Comment by mittalshravika** [comment]
Hi, I tried solving this issue by making the pinout diagram for tessel.
![tessel](https://user-images.githubusercontent.com/23384503/27993258-2a929654-64c4-11e7-92d0-a6e4dc3719de.jpg)
