### ISSUE TITLE
Tessel.io/opensource info port

### ISSUE THREAD

**Issue by Frijol** [tessel/t2-docs#145]
The [Hardware/Modules docs page](https://github.com/tessel/t2-docs/blob/master/Hardware/Modules.md) should include links to all the hardware information for all of the modules it lists.

Each module listed on the Modules page needs a new table or list of links including:

- Code: firmware, docs, examples
- Schematic (PDF)
- Schematic (DipTrace)
- Layout (DipTrace)
- Layout support file for silkscreen

These links can be found at https://tessel.io/opensource

Note that https://tessel.io/opensource lists some modules that are no longer supported– these should not be added to the Hardware/Modules page.

**Comment by Frijol** [comment]
related: https://github.com/tessel/tessel.io/issues/7

**Comment by mittalshravika** [comment]
Hey, Could you please assign the issue to me. i have started working on it.
