### ISSUE TITLE
"How do I know if I need to update" section should mention auto-notifications

### ISSUE THREAD

**Issue by Frijol** [tessel/t2-docs#146]
https://tessel.gitbooks.io/t2-docs/content/API/CLI.html#how-do-i-know-if-i-need-to-update-my-t2

The "How do I know..." section linked above should mention what you will get automatic updates about. Specifically, it should mention that:

* The CLI will tell you if you are running an old version of CLI if you are connected to the internet and have a version newer than (when did this get introduced?) when you run any t2 command
* The CLI will not tell you if you are running an old version of firmware

**Comment by mittalshravika** [comment]
Hey, I worked on this Issue. @Frijol you may review the same.

**Comment by mittalshravika** [comment]
Hey, I had a query that for this issue we need to mention that there is no automatic way in which the user can be made aware that there is a newer version for t2-firmware in the t2-docs?

Is anything else also required for resolving this?

**Comment by Frijol** [comment]
I'm not sure I understand your question.

I would suggest:
* Mention how you'd know if t2-cli needs an update via the notifier
* Mention that you would not know if firmware or CLI needs an update but that the fastest way to find out is to run `t2 update`

**Comment by mittalshravika** [comment]
Hey, I tried connecting wifi to the other Tessel we have, but it did not give an update notification for t2-cli as it had given earlier.

**Comment by rwaldron** [comment]
> Hey, I tried connecting wifi to the other Tessel we have, but it did not give an update notification for t2-cli as it had given earlier.
>
> Is it because of that 24 hour functionality?

Are you referring to this: https://www.npmjs.com/package/update-notifier#updatecheckinterval ? If yes, then I think you're right.

**Comment by Frijol** [comment]
reopened; incorrectly auto-closed with a PR merge

**Comment by mittalshravika** [comment]
@Frijol, created a PR for this issue. You may review the same.
