### ISSUE TITLE
`t2 restore` is undocumented

### ISSUE THREAD

**Issue by Frijol** [tessel/t2-docs#153]
`t2 restore` isn't documented in docs. CLI documents it as: "Restore your Tessel by installing the factory version of OpenWrt."

This is a very useful command! But I don't remember how it works, do you just plug in a tessel and run it without waiting for bootup? Do you have to put T2 into DFU mode?

**Comment by Frijol** [comment]
DFU mode: "device firmware upgrade mode". On Tessel 2, I believe this is activated by holding down the button on the board while plugging in Tessel (normally, with USB). Lights will flash a bit differently, and you should be able to run T2 CLI commands (but not the usual ones)

**Comment by rwaldron** [comment]
When running `t2 restore`, the command will put the Tessel 2 into DFU mode automatically—it _must_ begin in normal operation mode.

**Comment by Jeff-Duke** [comment]
I'd like to grab this if it hasn't been picked up already.  I can run the command on my Tessel this weekend to observe how it goes and document the results.

**Comment by HipsterBrown** [comment]
Thanks for picking this up @Jeff-Duke. You can ping me here or in the [Tessel Slack](https://slackin.tessel.io) if you have any questions.

**Comment by Jeff-Duke** [comment]
Thanks @HipsterBrown!

**Comment by Jeff-Duke** [comment]
I've opened PR #184 for this.
