### ISSUE TITLE
Link for GPIO pins directing to a page that cannot be found

### ISSUE THREAD

**Issue by mittalshravika** [tessel/t2-docs#156]
In the t2 documentation for [GPIO](https://tessel.gitbooks.io/t2-docs/content/Tutorials/Communication_Protocols.html#gpio), the sentence "See which pins support this protocol" is directing to a [page](https://github.com/tessel/t2-docs/blob/master/hardware-api.md#pin-mapping) that cannot be found. 

Instead, it should be directed to tessel [pin-mapping](https://tessel.gitbooks.io/t2-docs/content/API/Hardware_API.html#pin-mapping).

**Comment by solderneer** [comment]
#157 
Hi, I've fixed it in this pull request!
