### ISSUE TITLE
Link for Technical overview leading to a page that cannot be found

### ISSUE THREAD

**Issue by mittalshravika** [tessel/t2-docs#161]
In the [Introduction Section](https://tessel.gitbooks.io/t2-docs/content/#welcome-to-the-tessel-2-documentation) of t2-docs, the phrase "Technical Overview" is directing to a [page](https://tessel.gitbooks.io/t2-docs/content/debugging/Technical_Overview.html) that cannot be found

Instead it should be directed to [Tessel 2 Technical Overview](https://tessel.gitbooks.io/t2-docs/content/Debugging/Technical_Overview.html) under the Debugging section.

**Comment by mittalshravika** [comment]
@Frijol, the commit for this PR got merged along with #162.

**Comment by Frijol** [comment]
thanks, closing!
