### ISSUE TITLE
Pinout diagram not rendering in t2 docs

### ISSUE THREAD

**Issue by Frijol** [tessel/t2-docs#170]
Pin mapping diagram is not rendering in the Hardware API (below the pinout table):

![screen shot 2017-08-08 at 11 12 57 am](https://user-images.githubusercontent.com/454690/29087386-9b206522-7c2a-11e7-9f79-e2d63fa43bf9.png)

(thanks for the bug report, @mittalshravika )

Debugging:

First check: did it deploy properly to Gitbook https://www.gitbook.com/book/tessel/t2-docs/activity (looks like yes)

2nd check: does it render in the markdown on Github?
https://github.com/tessel/t2-docs/blob/master/API/Hardware_API.md ugh no

3rd check: filepath says `![Pin Mapping for Tessel](/images/pindiagram.jpg)`, so let’s look in the images folder

https://github.com/tessel/t2-docs/tree/master/images

it’s not there!

bug found: the image did not get committed to the folder

**Comment by Frijol** [comment]
@mittalshravika can you please fix?

**Comment by mittalshravika** [comment]
Yes I will definitely look into this.
