### ISSUE TITLE
Examples should be more consistent

### ISSUE THREAD

**Issue by Frijol** [tessel/t2-docs#19]
Let's pick: for callbacks, `err` or `error`?

**Comment by johnnyman727** [comment]
I vote `err`.

**Comment by HipsterBrown** [comment]
I vote for clearer, more verbose naming. If this is still relevant, I would prefer standardizing on `error`. 

I'm also looking at this as a good starter issue for new contributors.

**Comment by Frijol** [comment]
I agree, `error` is clearer to new contributors.
