### ISSUE TITLE
Arguments are illegible in near-white on white background

### ISSUE THREAD

**Issue by sdaitzman** [tessel/t2-docs#57]
Extremely low contrast ratio on that `(error, value)` after `function`:

<img width="572" alt="screen shot 2016-04-17 at 6 23 25 pm" src="https://cloud.githubusercontent.com/assets/1499476/14590481/75f299fc-04c9-11e6-8696-95d2f250b4d5.png">

**Comment by johnnyman727** [comment]
Yikes, that's no good.

I think @Frijol is in the midst of transitioning to gitbook so this problem be resolved pretty soon.

**Comment by Frijol** [comment]
oof, yeah. I loathe our current docs style (I think it's my fault anyway). @sdaitzman any thoughts on the Gitbook idea or associated PR? https://github.com/tessel/t2-docs/issues/50

**Comment by sdaitzman** [comment]
The new style is beautiful, especially on those tables! 😄
