### ISSUE TITLE
t2 ap --trigger on/off => t2 ap --on/--off

### ISSUE THREAD

**Issue by huseyinkozan** [tessel/t2-docs#75]
Hello,

I thing docs need to update. I tried on/off commands as `t2 wifi`, and it works. But not at the `t2 ap`.

**Comment by johnnyman727** [comment]
Thanks for catching this! Would you be willing to make the change? You'll need to edit [this file](https://github.com/tessel/t2-docs/blob/master/cli.md).

**Comment by huseyinkozan** [comment]
Ok, I will change it.
