### ISSUE TITLE
Sections are out of order

### ISSUE THREAD

**Issue by rwaldron** [tessel/t2-docs#79]
The TOC at the top lists: 
- PWM pins
- SPI
- I2C
- UART/Serial

But the sections are actually: 
- PWM pins
- I2C
- Terms Used
- SPI
- UART/Serial

I suggest reordering the sections to: 
- PWM pins
- Terms Used
- I2C
- SPI
- UART/Serial

And the TOC to match

**Comment by Frijol** [comment]
This will likely require some investigation into the build tools, since the TOC is automatically generated. You can see the build scripts in the package.json. We use this NPM package: https://www.npmjs.com/package/gitbook-summary

**Comment by Frijol** [comment]
I think my original comment was confused re which TOC, this should be a simple (albeit manual) text edit fix
