### ISSUE TITLE
Syntax Highlighting in code examples is hard to read

### ISSUE THREAD

**Issue by rwaldron** [tessel/t2-docs#83]
Of course, this is subjective, but there are parts that are actually completely unreadable, like the parameter list syntax of functions.

![](https://i.gyazo.com/96351ed5b4663756805467ba921f2545.png)

I suggest that we put all of these into gists that are embedded in the docs

**Comment by HipsterBrown** [comment]
This will be resolved by #51 - Making the docs into a GitBook. The code samples look much better and clearer in that build, which we should be releasing soonish.

**Comment by rwaldron** [comment]
Ah! Perfect—thank you!
