### ISSUE TITLE
T2 CLI docs do not include mention of `t2 root`

### ISSUE THREAD

**Issue by Frijol** [tessel/t2-docs#97]

**Comment by Frijol** [comment]
Btw, is there a better way to document CLI commands than here in this doc? Feels redundant with the documentation that's inherent to the CLI, e.g. you can just `t2 root -v` to learn in an up-to-date manner what is going on. cc @HipsterBrown maybe you have a thought about this

**Comment by Frijol** [comment]
Discussed live, we decided it's still useful to manually update the docs since this provides a different sort of insight than that provided by the CLI documentation – "why does this exist, and what is it" rather than just "how do I do this"

**Comment by Frijol** [comment]
The root command can be found in the CLI code (with some in-line docs) here: https://github.com/tessel/t2-cli/blob/master/lib/controller.js#L803

**Comment by Jeff-Duke** [comment]
PR open - https://github.com/tessel/t2-docs/pull/130
@Frijol @HipsterBrown
